# Generated by Django 5.1 on 2024-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
