# Generated by Django 5.1 on 2024-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_note_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="title",
        ),
    ]
