# Generated by Django 5.1 on 2024-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
